EdTech/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', HomePage.as_view() , name='home'),
    path('', include("courses.urls")),
    path('', include("students.urls")),
    path('', include("accounts.urls")),
    path('pay/<slug:slug>', pay_with_razor, name="razorpay"),       
    path('payment_successful/<slug:slug>', success_payment, name="payment_success"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

courses/urls.py
from django.urls import path
from .views import *

app_name = 'courses'

urlpatterns = [
    
    path('courses/<slug:slug>', CourseDetailView.as_view(), name='course-details'),
    path('courses/<slug:slug>/category', CoursesByCategoryListView.as_view(), name='course-by-category'),
    path('upload/', CreateCourseView.as_view(), name='create-course'),
    path('upload/<slug:slug>/lessons/', createLesson , name='create-lessons'),
    path('learn/lesson/<int:lesson_id>/', learn_lesson , name='lesson-page'),
    path('remove/<int:comment_id>/', comment_remove, name='comment_remove'),
    path('search', search, name="search"),
]

courses/models.py
from django.db import models
from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver
from django.utils.timezone import now
from django.utils.text import slugify
from django.contrib.auth import get_user_model
User = get_user_model()

class Category(models.Model):
    title = models.CharField(max_length=50, default='')
    slug = models.SlugField(max_length=200, unique=True, default='', blank=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'


class Course(models.Model):
    instructor = models.ForeignKey(User, on_delete=models.CASCADE, default='')
    title = models.CharField(max_length=100, default='')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, default='')
    slug = models.SlugField(max_length=200, unique=True, blank=True, primary_key=True, auto_created=False, default='')
    short_description = models.CharField(blank=False, max_length=150, default='')
    description = models.TextField(blank=False, default='')
    language = models.CharField(max_length=200, default='English')
    thumbnail = models.ImageField(upload_to='thumbnails/', default='')
    

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Course, self).save(*args, **kwargs)

    def add_user_to_list_of_students(self, user):
        registration = CourseRegistration.objects.create(user = user,
                                                    course = self)


class Lesson(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='lessons', default='')
    title = models.CharField(max_length=100, default=None)
    video = models.FileField(upload_to='courses/')

    def __str__(self):
        return self.course.title
    

class LessonComment(models.Model):
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField(max_length=200, default=None)
    reply = models.ForeignKey('self',on_delete=models.CASCADE, null=True, blank=True)
    timestamp = models.DateTimeField(default=now)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.user.username, self.lesson)



class CourseRegistration(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'Students'
        unique_together = ('course','user')

# @receiver(pre_delete, sender=Course)
# def mymodel_delete(sender, instance, **kwrags):
#     instance.video.delete(False)

courses/forms.py
from django import forms
from django.db.models import fields
from .models import Course, Lesson, LessonComment


class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['title', 'thumbnail', 'category', 'short_description', 'description', 'language']


class LessonForm(forms.ModelForm):
    class Meta:
        model = Lesson
        fields = ['title','video']

class CommentForm(forms.ModelForm):
    class Meta:
        model = LessonComment
        fields = ['comment']

        widgets = {
            'comment': forms.Textarea(attrs={
                'class': 'editable medium-editor-textarea',
                'rows':1, 
                'cols':100
            })
        }

courses/views.py
from django.http import Http404
from django.shortcuts import get_object_or_404, render,redirect
from django.urls import reverse_lazy
from django.contrib import messages
from django.views.generic import ListView, CreateView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from .models import *
from .forms import CourseForm, LessonForm, CommentForm

from django.forms import inlineformset_factory

class CourseDetailView(DetailView):
    model = Course
    template_name = 'courses/courses.html'
    context_object_name = 'course'

    def get_object(self, queryset=None):
        if queryset is None:
            queryset = self.get_queryset()

        slug = self.kwargs.get(self.slug_url_kwarg)
        slug_field = self.get_slug_field()
        queryset = queryset.filter(**{slug_field: slug})
        try:
            # Get the single item from the filtered queryset
            obj = queryset.get()
        except queryset.model.DoesNotExist:
            raise Http404("No %(verbose_name)s found matching the query" %
                          {'verbose_name': self.model._meta.verbose_name})
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        course = Course.objects.get(slug=self.kwargs['slug'])
        if self.request.user.is_authenticated:
            if CourseRegistration.objects.filter(course=course, user_id=self.request.user.id).exists():
                context['is_enrolled'] = True
                context['lessons'] = course.lessons.all()
            else:
                context['is_enrolled'] = False
                context['lessons'] = course.lessons.all()
        return context
    
    

class CoursesByCategoryListView(ListView):
    template_name = 'courses/courses_by_category.html'
    model = Course
    context_object_name = 'courses'

    def get_queryset(self):
        category = Category.objects.get(slug=self.kwargs['slug'])
        return self.model.objects.filter(category_id=category.id)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category = Category.objects.get(slug=self.kwargs['slug'])
        context['category'] = category
        context['categories'] = Category.objects.all()
        return context

    
class CreateCourseView(LoginRequiredMixin, CreateView):
    template_name = 'courses/upload_course.html'
    form_class = CourseForm
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.instructor = self.request.user
        self.object.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('courses:create-lessons', kwargs={'slug': self.object.slug})

def createLesson(request, slug):
    LessonFormSet = inlineformset_factory(Course, Lesson, fields=('title', 'video'), extra=5)
    course = Course.objects.get(slug=slug)
    formset = LessonFormSet(queryset=Lesson.objects.none(), instance=course)

    if request.method == 'POST':
        form = LessonForm(request.POST, request.FILES)
        formset = LessonFormSet(request.POST, request.FILES, instance=course)
        if formset.is_valid():
            formset.save()
            return redirect('home')

    context = {'form':formset}
    return render(request, 'courses/upload_lessons.html', context)


def learn_lesson(request, lesson_id):
    try:
        lesson_obj = Lesson.objects.get(id=lesson_id)
        comments = LessonComment.objects.filter(lesson = lesson_obj)
    except ObjectDoesNotExist:
        return render(request, '404.html')
    
    if request.method == 'POST':
            form = CommentForm(request.POST)
            if form.is_valid():
                comment = form.save(commit=False)
                comment.lesson = lesson_obj
                comment.user = request.user
                comment.save()
                messages.success(request, "Your comment has been posted successfully")
                return redirect(request.path)
    else:
        form = CommentForm()
    
    context = {
                'lesson':lesson_obj,
                'form':form,
                'comments':comments,
            }
    return render(request, 'courses/lessons.html', context)


def comment_remove(request, comment_id):
    comment = get_object_or_404(LessonComment, id=comment_id)
    lesson_id = comment.lesson.id
    comment.delete()
    return redirect('courses:lesson-page', lesson_id)


def search(request):
    query = request.GET.get('query')
    allCoursesTitle = Course.objects.filter(title__icontains=query)
    allCoursesInstructor = Course.objects.filter(instructor__username__icontains=query)
    allCourses = allCoursesTitle.union(allCoursesInstructor)
    if allCourses.count()==0:
        messages.warning(request,  "No search results found. Please refine your query.")
    context = {'allCourses': allCourses, 'query':query}
    return render(request, 'courses/search.html', context)

courses/templates/courses/courses_by_category.html
{% extends 'base.html' %}

{% load static %}
{% load bootstrap %}
{% block content %}
<div class="dark">
	<main class="container py-4">
		<div class="h1 text-center" id="pageHeaderTitle" style="color: white;"> {{ category.title }}</div>

      {% for course in courses %}
        <article class="postcard dark blue" style="max-height: 300px;">
          <a class="postcard__img_link" href="#">
            <img class="postcard__img" src="{{course.thumbnail.url}}" alt="Image Title" />	
          </a>
          <div class="postcard__text">
            <h1 class="postcard__title red"><a href="{% url 'courses:course-details' course.slug %}">{{ course.title }}</a></h1>
            <div class="postcard__subtitle small">					
                <p class="fas fa-calendar-alt mr-2"> {{ course.short_description }}	</p>			
            </div>
            <div class="postcard__bar"></div>
            <div class="postcard__preview-txt"> 
            <p>{{ course.instructor }}</p> 
            </div>
            <ul class="postcard__tagbox">
                      <a href="{% url 'courses:course-details' course.slug %}"><button type="button" class="btn btn-outline-warning" >DETAILS</button></a> 
            </ul>
          </div>
        </article>	
	    {% endfor %}
	</main>
</div>


    <style>  
          body{
            background: #110f16;
          }
          
          
          .light {
            background: #f3f5f7;
          }
          
          a,
          a:hover {
            text-decoration: none;
            transition: color 0.3s ease-in-out;
          }
          
          #pageHeaderTitle {
            margin: 2rem 0;
            text-transform: uppercase;
            text-align: center;
            font-size: 2.5rem;
          }
          
          /* Cards */
          .postcard {
            flex-wrap: wrap;
            display: flex;
            box-shadow: 0 4px 21px -12px rgba(0, 0, 0, 0.66);
            border-radius: 10px;
            margin: 0 0 2rem 0;
            overflow: hidden;
            position: relative;
            color: #ffffff;
          }
          .postcard.dark {
            background-color: #18151f;
          }
          .postcard.light {
            background-color: #e1e5ea;
          }
          .postcard .t-dark {
            color: #18151f;
          }
          .postcard a {
            color: inherit;
          }
          .postcard h1,
          .postcard .h1 {
            margin-bottom: 0.5rem;
            font-weight: 500;
            line-height: 1.2;
          }
          .postcard .small {
            font-size: 17px;
          }
          .postcard .postcard__title {
            font-size: 1.75rem;
          }
          .postcard .postcard__img {
            max-height: 180px;
            width: 100%;
            object-fit: cover;
            position: relative;
          }
          .postcard .postcard__img_link {
            display: contents;
          }
          .postcard .postcard__bar {
            width: 50px;
            height: 10px;
            margin: 10px 0;
            border-radius: 5px;
            background-color: #424242;
            transition: width 0.2s ease;
          }
          .postcard .postcard__text {
            padding: 1.5rem;
            position: relative;
            display: flex;
            flex-direction: column;
          }
          .postcard .postcard__preview-txt {
            overflow: hidden;
            text-overflow: ellipsis;
            text-align: justify;
            height: 100%;
            font-size: 15px;
          }
          .postcard .postcard__tagbox {
            display: flex;
            flex-flow: row wrap;
            font-size: 14px;
            margin: 20px 0 0 0;
            padding: 0;
            justify-content: center;
          }
          .postcard .postcard__tagbox .tag__item {
            display: inline-block;
            background: rgba(83, 83, 83, 0.4);
            border-radius: 3px;
            padding: 2.5px 10px;
            margin: 0 5px 5px 0;
            cursor: default;
            user-select: none;
            transition: background-color 0.3s;
          }
          .postcard .postcard__tagbox .tag__item:hover {
            background: rgba(83, 83, 83, 0.8);
          }
          .postcard:before {
            content: "";
            position: absolute;
            top: 0;
            right: 0;
            bottom: 0;
            left: 0;
            background-image: linear-gradient(-70deg, #424242, transparent 50%);
            opacity: 1;
            border-radius: 10px;
          }
          .postcard:hover .postcard__bar {
            width: 100px;
          }

          @media screen and (min-width: 769px) {
            .postcard {
              flex-wrap: inherit;
            }
            .postcard .postcard__title {
              font-size: 1.6rem;
            }
            .postcard .postcard__tagbox {
              justify-content: start;
            }
            .postcard .postcard__img {
              max-width: 300px;
              max-height: 100%;
              transition: transform 0.3s ease;
            }
            .postcard .postcard__text {
              padding: 3rem;
              width: 100%;
            }
            .postcard .media.postcard__text:before {
              content: "";
              position: absolute;
              display: block;
              background: #18151f;
              top: -20%;
              height: 130%;
              width: 55px;
            }
            .postcard:hover .postcard__img {
              transform: scale(1.1);
            }
            .postcard:nth-child(2n+1) {
              flex-direction: row;
            }
            .postcard:nth-child(2n+0) {
              flex-direction: row-reverse;
            }
            .postcard:nth-child(2n+1) .postcard__text::before {
              left: -12px !important;
              transform: rotate(4deg);
            }
            .postcard:nth-child(2n+0) .postcard__text::before {
              right: -12px !important;
              transform: rotate(-4deg);
            }
          }
          @media screen and (min-width: 1024px) {
            .postcard__text {
              padding: 2rem 3.5rem;
            }
          
            .postcard__text:before {
              content: "";
              position: absolute;
              display: block;
              top: -20%;
              height: 130%;
              width: 55px;
            }
          
            .postcard.dark .postcard__text:before {
              background: #18151f;
            }
          
            .postcard.light .postcard__text:before {
              background: #e1e5ea;
            }
          }
          /* COLORS */
          .postcard .postcard__tagbox .green.play:hover {
            background: #79dd09;
            color: black;
          }
          
          .green .postcard__title:hover {
            color: #79dd09;
          }
          
          .green .postcard__bar {
            background-color: #79dd09;
          }
          
          .green::before {
            background-image: linear-gradient(-30deg, rgba(121, 221, 9, 0.1), transparent 50%);
          }
          
          .green:nth-child(2n)::before {
            background-image: linear-gradient(30deg, rgba(121, 221, 9, 0.1), transparent 50%);
          }
          
          .postcard .postcard__tagbox .blue.play:hover {
            background: #0076bd;
          }
          
          .blue .postcard__title:hover {
            color: #0076bd;
          }
          
          .blue .postcard__bar {
            background-color: #0076bd;
          }
          
          .blue::before {
            background-image: linear-gradient(-30deg, rgba(0, 118, 189, 0.1), transparent 50%);
          }
          
          .blue:nth-child(2n)::before {
            background-image: linear-gradient(30deg, rgba(0, 118, 189, 0.1), transparent 50%);
          }
          
          .postcard .postcard__tagbox .red.play:hover {
            background: #bd150b;
          }
          
          .red .postcard__title:hover {
            color: #bd150b;
          }
          
          .red .postcard__bar {
            background-color: #bd150b;
          }
          
          .red::before {
            background-image: linear-gradient(-30deg, rgba(189, 21, 11, 0.1), transparent 50%);
          }
          
          .red:nth-child(2n)::before {
            background-image: linear-gradient(30deg, rgba(189, 21, 11, 0.1), transparent 50%);
          }
          
          .postcard .postcard__tagbox .yellow.play:hover {
            background: #bdbb49;
            color: black;
          }
          
          .yellow .postcard__title:hover {
            color: #bdbb49;
          }
          
          .yellow .postcard__bar {
            background-color: #bdbb49;
          }
          
          .yellow::before {
            background-image: linear-gradient(-30deg, rgba(189, 187, 73, 0.1), transparent 50%);
          }
          
          .yellow:nth-child(2n)::before {
            background-image: linear-gradient(30deg, rgba(189, 187, 73, 0.1), transparent 50%);
          }
          
          @media screen and (min-width: 769px) {
            .green::before {
              background-image: linear-gradient(-80deg, rgba(121, 221, 9, 0.1), transparent 50%);
            }
          
            .green:nth-child(2n)::before {
              background-image: linear-gradient(80deg, rgba(121, 221, 9, 0.1), transparent 50%);
            }
          
            .blue::before {
              background-image: linear-gradient(-80deg, rgba(0, 118, 189, 0.1), transparent 50%);
            }
          
            .blue:nth-child(2n)::before {
              background-image: linear-gradient(80deg, rgba(0, 118, 189, 0.1), transparent 50%);
            }
          
            .red::before {
              background-image: linear-gradient(-80deg, rgba(189, 21, 11, 0.1), transparent 50%);
            }
          
            .red:nth-child(2n)::before {
              background-image: linear-gradient(80deg, rgba(189, 21, 11, 0.1), transparent 50%);
            }
          
            .yellow::before {
              background-image: linear-gradient(-80deg, rgba(189, 187, 73, 0.1), transparent 50%);
            }
          
            .yellow:nth-child(2n)::before {
              background-image: linear-gradient(80deg, rgba(189, 187, 73, 0.1), transparent 50%);
            }
          }    
    </style>  

{% endblock %}

courses/templates/courses/lessons.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% block content %}

<div class="container"></div>
<div class="row">
<div class="col-lg-1"></div>
<div class="col-lg-10">
<div class="my-5">
    <video name='demo' controls width='1250px' height='600px'>
        <source src="{{lesson.video.url}}" type="video/mp4"></source>
    </video>
</div>

<hr>

<div class="row">
<div class="col-lg-2"></div>
<div class="col-lg-8">
<h4>All comments in this lesson ({{comments.count}})</h4>
<hr>
{% for comment in comments %}
    <div class="row my-3">
        <div class="col-md-1  ">
            <img class="profile-pic" src="{{comment.user.profile.profile_pic.url}}">
        </div>
        <div class="col-md-10"> 
        <b> {{comment.user.username}} </b> at {{comment.timestamp}}
        <div>   {{comment.comment}} </div>
        </div>
        {% if user == comment.user %}
        <div class="col-md-1">
            <a href="{% url 'courses:comment_remove' comment.id %}"><i style="color: red;" class="fa fa-trash" aria-hidden="true"></i></a>
        </div>
        {% endif %}
    </div>
    <hr>
{% endfor %}

<br>

<div class="">
  <h5>Add a comment</h5>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-primary btn-small" value="Submit">
    </form>
</div>
</div>
<div class="col-lg-2"></div>
</div>

</div>
<div class="col-lg-1"></div>
</div>
</div>


<style>
    body{
        overflow-x: hidden;
    }
    .box{
        margin: 30px 0;
    }
    .profile-pic{
        height: 50px;
        width: 50px;
        border-radius: 50%;
    }
</style>
{% endblock %}

courses/templates/courses/upload_course.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% block content %}


<div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-6">
        <div class="container" style="width:700px;margin-top:20px;padding:20px;opacity:0.8;border-radius:30px;">
        <div >
            <div class="p-3 mb-2  text-white text-center" style="background-color:rgb(10, 7, 59)">ADD A COURSE</div>
            <form method="POST" enctype="multipart/form-data" >
                {% csrf_token %}
                {% bootstrap_form form %}
                <input type="submit" class="btn btn-primary btn-large" value="Add">
            </form>
        </div>
        </div>
    </div>
    <div class="col-lg-3"></div>
</div>


<style>
    body {
        display: block;
        position: relative;
        overflow-x: hidden;
      }
      
      body::after {
        content: "";
        background-image: url('{% static "images/4380.jpg" %}');
        background-attachment: fixed;
        background-repeat: no-repeat;
        background-size: cover;
        opacity: 0.4;
        top: 0;
        left: 0;
        bottom: 0;
        right: 0;
        position: absolute;
        z-index: -1;   
      }
    
</style>

{% endblock %}

courses/templates/courses/upload_lessons.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% block content %}
<div class="row">
    <div class="col-lg-3"></div>
    <div class="col-lg-6">
        <div class="container" style="width:700px;margin-top:20px;padding:20px;opacity:0.8;border-radius:30px;">
        <div>
            <div class="p-3 mb-2  text-white text-center" style="background-color:rgb(10, 7, 59)">ADD LESSONS</div>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" class="btn btn-primary btn-large" value="Add">
            </form>
        </div>
        </div>
    </div>
    <div class="col-lg-3"></div>
</div>

<style>
    body {
        display: block;
        position: relative;
        overflow-x: hidden;
      }
      
      body::after {
        content: "";
        background-image: url('{% static "images/4380.jpg" %}');
        background-attachment: fixed;
        background-repeat: no-repeat;
        background-size: cover;
        opacity: 0.4;
        top: 0;
        left: 0;
        bottom: 0;
        right: 0;
        position: absolute;
        z-index: -1;   
      }
    
</style>
{% endblock %}