EdTech/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('', HomePage.as_view() , name='home'),
    path('', include("courses.urls")),
    path('', include("students.urls")),
    path('', include("accounts.urls")),
    path('pay/<slug:slug>', pay_with_razor, name="razorpay"),       
    path('payment_successful/<slug:slug>', success_payment, name="payment_success"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import *

app_name = 'accounts'

urlpatterns = [
    
    path('register/', SignUpView.as_view() , name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name="accounts/login.html", redirect_authenticated_user=True), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('user', profile , name='account_settings'),
    path('my-courses/', registered_courses , name='my_courses'),
]

courses/urls.py
from django.urls import path
from .views import *

app_name = 'courses'

urlpatterns = [
    
    path('courses/<slug:slug>', CourseDetailView.as_view(), name='course-details'),
    path('courses/<slug:slug>/category', CoursesByCategoryListView.as_view(), name='course-by-category'),
    path('upload/', CreateCourseView.as_view(), name='create-course'),
    path('upload/<slug:slug>/lessons/', createLesson , name='create-lessons'),
    path('learn/lesson/<int:lesson_id>/', learn_lesson , name='lesson-page'),
    path('remove/<int:comment_id>/', comment_remove, name='comment_remove'),
    path('search', search, name="search"),
]

templates/base.html
{% load static %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>A-Plus</title>

    {% include 'header.html' %} 
</head>
<body>
    {% include 'navbar.html' %}
    
    {% block content %}

    {% endblock %}

</body>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>


</html>

templates/header.html
{% load static %}
<!-- Bootstrap -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">


<!-- Css -->


<!-- Font Awesome -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<!-- Google FOnts -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@600&display=swap" rel="stylesheet">

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap" rel="stylesheet">

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<style>
    hr{
        background-color: rgba(250, 250, 250, 0.1);
    }
        #header{
            height: 600px;
            position: relative;
            background-color: white;
            margin-bottom: 30px;
        }
        .header-image{
            top: 10%;
            right: 10%;
            position: absolute;
        }
        .header-image img{
            height: 520px;
            width: 600px;
        }
        .header-text { 
            position: absolute; 
            top: 30%; 
            left: 10%;
            right: 50%; 
            font-size: 65px;
            color: black;
            font-family: 'Poppins', sans-serif;
        }
        .header-desc {
            position: absolute; 
            top: 60%; 
            left: 10%; 
            right: 55%;
            font-size: 20px;
            font-weight: 400;
            color: black;
            text-align: justify;
            
        }

        /* Our-students */
        #our-students {
            margin: 20px 50px;
            height: 200px;
        }

        .heading h3{
            margin-top: 40px;
            text-align: center;
            font-size: 24px;
        }

        .logo{
            width: 20%;
            margin: 20px 30px;
            float: left;
            position: relative;
            text-align: center;
        }

        .logo img{
            height: 150px;
            width: 150px;
            position: relative;
        }

        /* top-selling courses */

        .card {
        box-shadow: 0 0 10px 0 rgba(100, 100, 100, 0.26);
        }

        #top-courses {
            margin: 25px 120px;
        }
        .course-image {
            height: 240px;
            width: 100%;
        }

        .competition-content h5{
            font-family: 'Roboto', sans-serif;
            font-size: 30px;
        }
        .text-color{
            color: black;
            font-size: 16px;
            line-height: 1.75;
        }

        /* footer */

        .footer-dark {
        padding:50px 0;
        color:#f0f9ff;
        background-color:#282d32;
        }

        .footer-dark h3 {
        margin-top:0;
        margin-bottom:12px;
        font-weight:bold;
        font-size:16px;
        }

        .footer-dark ul {
        padding:0;
        list-style:none;
        line-height:1.6;
        font-size:14px;
        margin-bottom:0;
        }

        .footer-dark ul a {
        color:inherit;
        text-decoration:none;
        opacity:0.6;
        }

        .footer-dark ul a:hover {
        opacity:0.8;
        }

        .footer-dark .item.text {
        margin-bottom:36px;
        }

        .footer-dark .item.text p {
        opacity:0.6;
        margin-bottom:0;
        }

        .footer-dark .item.social {
        text-align:center;
        }


        .footer-dark .item.social > a {
        font-size:20px;
        width:36px;
        height:36px;
        line-height:36px;
        display:inline-block;
        text-align:center;
        border-radius:50%;
        box-shadow:0 0 0 1px rgba(255,255,255,0.4);
        margin:0 8px;
        color:#fff;
        opacity:0.75;
        }

        .footer-dark .item.social > a:hover {
        opacity:0.9;
        }

        .footer-dark .copyright {
        text-align:center;
        padding-top:24px;
        opacity:0.5;
        font-size:13px;
        margin-bottom:0;
        }

</style>

    <section id="header">
        <h2 class="header-text">Learn Without Limits</h2>
        <div class="header-image">
            <img src="{% static 'images/bg-img.png' %}" alt="">
        </div>
        <p class="header-desc">Discover the fastest, most effective way to gain job-ready expertise for the careers of the future.</p>
    </section>

    <hr>
    <div class="heading">
        <h3>We have students from 100+ colleges and companies</h3>
    </div>
    <section id="our-students">
        <div class="logo">
            <img src="{% static 'images/iit-b.png' %}" alt="">
        </div>
        <div class="logo">
            <img src="{% static 'images/iit-d.png' %}" alt="">
        </div>
        <div class="logo">
            <img src="{% static 'images/adobe.png' %}" alt="">
        </div>
        <div class="logo">
            <img src="{% static 'images/apple.png' %}" alt="">
        </div>
    </section>

    <hr>

    <div class="heading">
        <h3>Top-selling Courses</h3>
    </div>
    <section id="top-courses">
        <div class="row">
        <div class="col-lg-4 mb-4 d-flex align-items-stretch">
            <div class="card card-bg">
                <img src="{% static 'images/python.jpg' %}" alt="" class="card-img-top course-image">
                <div class="card-body"> 
                    <div class="course-content">
                        <h5 class="card-title">Python For Begineers</h5>
                        <p class="card-text text-color">This Python For Beginners Course Teaches You The Python Language Fast. Includes Python Online Training With Python 3</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-4 mb-4 d-flex align-items-stretch">
            <div class="card card-bg">
                <img src="{% static 'images/java.jpg' %}" alt="" class="card-img-top course-image">
                <div class="card-body"> 
                    <div class="course-content">
                        <h5 class="card-title">Advanced Java</h5>
                        <p class="card-text text-color">Learn Java In This Course And Become a Computer Programmer. Obtain valuable Core Java Skills And Java Certification</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-4 mb-4 d-flex align-items-stretch">
            <div class="card card-bg">
                <img src="{% static 'images/photoshop.jpg' %}" alt="" class="card-img-top course-image">
                <div class="card-body"> 
                    <div class="course-content">
                        <h5 class="card-title">Adobe Photoshop 2021</h5>
                        <p class="card-text text-color">This Adobe Photoshop Essentials course will teach you Photoshop Retouching as well as Photoshop for graphic design.</p>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </section>

    <div class="footer-dark">
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-lg-4 item text">
                        <h3>Location</h3>
                        <p>22, Lorem ipsum dolor, consectetur adipiscing</p>
                        <p class="mb-0"><i class="fa fa-phone mr-3"></i>(531) 554-3410</p>
                        <p><i class="fa fa-envelope-o mr-3"></i>info@aplus.com</p>
                    </div>
                    <div class="col-lg-4 item">
                        <h3>About</h3>
                        <ul>
                            <li><a href="#">Company</a></li>
                            <li><a href="#">Team</a></li>
                            <li><a href="#">Careers</a></li>
                        </ul>
                    </div>
                    <div class="col-lg-4 item text">
                        <h3>A-plus</h3>
                        <p>A-plus is an online E-learning platform that connects thousands of students with the skills they need to succeed. A-plus as of July 2021</p>
                    </div>
                    <div class="col item social">
                        <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                        <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                        <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                    </div>
                </div>
                <p class="copyright">A-plus © 2021</p>
            </div>
        </footer>
    </div>

{% endblock %}

templates/navbar.html
{% load static %}

<style>
    #app-navbar nav{
        background-color: black;
        padding: 3px 120px;
    }
    #app-navbar .navbar-brand a{
        color: white;
        font-size: 26px;
    }
    #app-navbar ul .nav-item a{
        font-size: 16px;
        text-decoration: none;
        color:  white;
    }
    #app-navbar ul .dropdown a{
        padding: 20px;
        color: white;
    }
    #app-navbar ul .dropdown .profile-pic{
        height: 50px;
        width: 50px;
        border-radius: 50%;
        margin-left: 15px;
    }
    #app-navbar ul .dropdown-menu{
        width: 220px;
    }
    #app-navbar ul .dropdown-menu a{
        padding: 4px 20px;
        color: black;
        text-decoration: none;
        font-size: 15px;
    }
    #app-navbar ul .dropdown-menu a:active{
        background-color: rgb(241, 241, 241);
    }
    #app-navbar .right-side .nav-link {
        padding: 20px;
    }
    #app-navbar .search-bar input{
        width: 200px;
    }
    
</style>

<div id="app-navbar">
    <nav class="navbar navbar-expand-md navbar-dark navbar-custom">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
                <li class="active navbar-brand">
                    <a class="nav-link" href="{% url 'home' %}">A-Plus<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Categories
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% for category in categories %}
                            <a class="dropdown-item" href="{% url 'courses:course-by-category' category.slug %}">
                                <i style="margin-right: 20px;" class="fa fa-angle-right" aria-hidden="true"></i>
                                <span>{{ category.title }}</span>
                            </a>
                        {% endfor %}
                    </div>
                </li>
            </ul>
            <form method="GET" action="/search" class="form-inline my-2 my-lg-0 ml-auto search-bar">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="query" id="search">
                <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Search</button>
            </form>
            <ul class="navbar-nav right-side">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'courses:create-course' %}">Teach on A+</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Account
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <p><img class="profile-pic" src="{{request.user.profile.profile_pic.url}}"> {{request.user.email}}</p>
                      <hr>
                      <a class="dropdown-item" href="{% url 'accounts:account_settings' %}">My Profile</a>
                      <a class="dropdown-item" href="{% url 'accounts:my_courses' %}">My Courses</a>
                      <a style="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
                    </div>
                </li>
                {% else %}
                    <li><span style="margin:5px"></span><a style="color:white; text-decoration: none;" href="{% url 'accounts:signup' %}"></span>Sign Up</a></li>
                    <li><span style="margin:5px"></span><span style="margin:5px"></span><a style="color:white; text-decoration: none;" href="{% url 'accounts:login' %}">Log In</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
</div>

templates/pay_base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <script src="https://kit.fontawesome.com/47101d2035.js" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Register</title>
</head>

<body>
    {% block content %}

    {% endblock content %} 
</body>

</html>

templates/pay_index.html
{% extends 'pay_base.html' %}

{% block content %}


<head>
    <style>
        .center {
            position: absolute;
            left: 50%;
            top: 50%;
            transform: translate(-50%, -50%);
        }
    </style>
</head>

<div class="center">

    <form class="text-center border border-light p-5" action="{% url 'payment_success' slug %}" method="POST">
        {% csrf_token %}

        <p class="h3 mb-3"><i class="fa fa-calendar-o" aria-hidden="true"></i>BUY THIS COURSE!!</p>

        <!-- RAZORPAY INTEGRATION HERE -->
        <script src="https://checkout.razorpay.com/v1/checkout.js" 
        data-key="TEST_KEY" 
        data-amount="5000"
        data-currency="INR" 
        data-order_id="{{payment.id}}" 
        data-buttontext="Pay with Razorpay"
        data-name="A-Plus"
        data-description="A+ Course"
        data-prefill.name="PC"
        data-theme.color="#0059ff"></script>

    </form>

</div>

</div>
{% endblock %}

templates/pay_success.html
  
{% extends 'pay_base.html' %}

{% block content %}

<head>
    <style>
        .center {
            position: absolute;
            text-align: center;
            left: 50%;
            top: 50%;
            transform: translate(-50%, -50%);
        }
    </style>
</head>

<body>
    <div class="center">
        <h3>
            Thanks, You have successfully registered for this event! <i class="fas fa-check-circle"></i>
        </h3>
        <h5>
            <a href="http://127.0.0.1:8000/">
                Again?
            </a>
        </h5>
    </div> 
</body>

{% endblock content %}